// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Airport struct {
	Icao       *string     `json:"icao,omitempty"`
	Iata       *string     `json:"iata,omitempty"`
	Name       *string     `json:"name,omitempty"`
	City       *string     `json:"city,omitempty"`
	State      *string     `json:"state,omitempty"`
	Country    *string     `json:"country,omitempty"`
	Coordinate *Coordinate `json:"coordinate,omitempty"`
	Timezone   *string     `json:"timezone,omitempty"`
}

type Coordinate struct {
	Longitude *float64 `json:"longitude,omitempty"`
	Latitude  *float64 `json:"latitude,omitempty"`
	Elevation *int     `json:"elevation,omitempty"`
}

type Query struct {
}
